package Modelo;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

public class Coordinator extends User {
    
    public Coordinator(String id, String name, String password) {
        super(id, name, password);
    }
    
    @Override
    public String getRole() {
        return "COORDINATOR";
    }
    
    // ==================== RF-9: USER MANAGEMENT ====================
    
    public void createUser(User user, List<User> userList) {
        if (user == null || userList == null) return;
        userList.add(user);
        System.out.println("✅ User created: " + user.getName() + " (" + user.getRole() + ")");
    }
    
    public void editUser(User user, String newName, String newPassword) {
        if (user == null) return;
        if (newName != null && !newName.trim().isEmpty()) {
            user.setName(newName);
        }
        if (newPassword != null && !newPassword.trim().isEmpty() && newPassword.length() >= 4) {
            user.setPassword(newPassword);
        }
        System.out.println("✅ User edited: " + user.getName());
    }
    
    public void disableUser(User user) {
        if (user == null) return;
        user.setActive(false);
        System.out.println("✅ User disabled: " + user.getName());
    }
    
    public void enableUser(User user) {
        if (user == null) return;
        user.setActive(true);
        System.out.println("✅ User enabled: " + user.getName());
    }
    
    public void listAllUsers(List<User> userList) {
        if (userList == null || userList.isEmpty()) {
            System.out.println("No users found");
            return;
        }
        System.out.println("\n" + line(70));
        System.out.println("ALL USERS");
        System.out.println(line(70));
        for (User user : userList) {
            System.out.println(user.getId() + " | " + user.getName() + " | " + user.getRole() + " | Active: " + user.isActive());
        }
        System.out.println(line(70));
        System.out.println("Total: " + userList.size());
    }
    
    // ==================== RF-10: CANCEL OBSERVATION ====================
    
    public void cancelObservation(Observation observation, String justification) {
        if (observation == null) {
            System.out.println("Cannot cancel null observation");
            return;
        }
        observation.cancel(this, justification);
    }
    
    // ==================== RF-11: GENERATE REPORTS ====================
    
    public Report generateGeneralReport(List<Student> allStudents) {
        if (allStudents == null) allStudents = new ArrayList<>();
        
        StringBuilder content = new StringBuilder();
        String date = LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));
        
        content.append("GENERAL COEXISTENCE REPORT\n");
        content.append(line(50)).append("\n");
        content.append("Generated by: ").append(this.getName()).append("\n");
        content.append("Date: ").append(date).append("\n");
        content.append(line(50)).append("\n\n");
        
        int totalStudents = allStudents.size();
        int totalObservations = 0;
        int totalDisciplinary = 0;
        int totalAcademic = 0;
        
        for (Student student : allStudents) {
            totalObservations += student.getTotalObservations();
            totalDisciplinary += student.getDisciplinaryObservations().size();
            totalAcademic += student.getAcademicObservations().size();
        }
        
        content.append("STATISTICS\n");
        content.append(line(40)).append("\n");
        content.append("Total Students: ").append(totalStudents).append("\n");
        content.append("Total Observations: ").append(totalObservations).append("\n");
        content.append("  Disciplinary: ").append(totalDisciplinary).append("\n");
        content.append("  Academic: ").append(totalAcademic).append("\n");
        content.append("Average per student: ");
        content.append(String.format("%.2f", totalStudents > 0 ? (double) totalObservations / totalStudents : 0));
        content.append("\n\n");
        
        content.append("STUDENTS WITH MOST OBSERVATIONS\n");
        content.append(line(40)).append("\n");
        
        List<Student> sorted = new ArrayList<>(allStudents);
        sorted.sort((s1, s2) -> Integer.compare(s2.getTotalObservations(), s1.getTotalObservations()));
        
        int count = Math.min(5, sorted.size());
        for (int i = 0; i < count; i++) {
            Student s = sorted.get(i);
            content.append((i + 1) + ". " + s.getName() + " - " + s.getTotalObservations() + " observations\n");
        }
        
        return new Report(content.toString(), this.getName(), "GENERAL");
    }
    
    public Report generateStudentReport(Student student) {
        if (student == null) {
            return new Report("No student provided", this.getName(), "STUDENT");
        }
        return Report.createStudentReport(student, this.getName());
    }
    
    public Report generateGradeReport(Grade grade) {
        if (grade == null) {
            return new Report("No grade provided", this.getName(), "GRADE");
        }
        return Report.createGradeReport(grade, this.getName());
    }
    
    // ==================== RF-12: ROLE ASSIGNMENT ====================
    
    public void assignGroupTeacherToGrade(Grade grade, GroupTeacher groupTeacher) {
        if (grade == null || groupTeacher == null) return;
        grade.setDocenteGrupo(groupTeacher);
        System.out.println("✅ Group Teacher " + groupTeacher.getName() + " assigned to " + grade.getName());
    }
    
    public void assignRepresentativeToGrade(Grade grade, Representative representative) {
        if (grade == null || representative == null) return;
        grade.setRepresentante(representative);
        System.out.println("✅ Representative " + representative.getName() + " assigned to " + grade.getName());
    }
    
    public GroupTeacher createGroupTeacher(Teacher teacher, String newId) {
        if (teacher == null) return null;
        GroupTeacher gt = new GroupTeacher(newId, teacher.getName(), teacher.getPassword());
        gt.setActive(teacher.isActive());
        System.out.println("✅ Group Teacher created: " + gt.getName());
        return gt;
    }
    
    public Representative createRepresentative(Student student, String newId) {
        if (student == null) return null;
        Representative rep = new Representative(newId, student.getName(), student.getPassword());
        rep.setActive(student.isActive());
        rep.setGrade(student.getGrade());
        for (Observation obs : student.getObservations()) {
            rep.addObservation(obs);
        }
        System.out.println("✅ Representative created: " + rep.getName());
        return rep;
    }
    
    // ==================== UTILITY METHODS ====================
    
    private String line(int length) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < length; i++) {
            sb.append("=");
        }
        return sb.toString();
    }
    
    public void printDashboard(List<Student> allStudents, List<User> allUsers) {
        System.out.println("\n" + line(60));
        System.out.println("COORDINATOR DASHBOARD");
        System.out.println(line(60));
        System.out.println("Coordinator: " + this.getName());
        System.out.println("Date: " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss")));
        System.out.println(line(60));
        
        if (allUsers != null) {
            long students = allUsers.stream().filter(u -> u instanceof Student).count();
            long teachers = allUsers.stream().filter(u -> u instanceof Teacher && !(u instanceof GroupTeacher)).count();
            long coordinators = allUsers.stream().filter(u -> u instanceof Coordinator).count();
            
            System.out.println("Total Users: " + allUsers.size());
            System.out.println("  Students: " + students);
            System.out.println("  Teachers: " + teachers);
            System.out.println("  Coordinators: " + coordinators);
        }
        
        if (allStudents != null) {
            int totalObs = 0;
            for (Student s : allStudents) {
                totalObs += s.getTotalObservations();
            }
            System.out.println("\nTotal Observations: " + totalObs);
            System.out.println("Average per student: " + 
                (allStudents.isEmpty() ? 0 : String.format("%.2f", (double) totalObs / allStudents.size())));
        }
        
        System.out.println(line(60));
    }
    
    @Override
    public String toString() {
        return "Coordinator{id='" + id + "', name='" + name + "', active=" + active + "}";
    }
}