package Modelo;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

public class Report {

    // ============================ ATRIBUTOS ============================
    
    private String content;           // Report content
    private LocalDateTime generationDate;  // When the report was generated
    private String generatedBy;       // Who generated the report (name or role)
    private String reportType;        // Type of report (GENERAL, STUDENT, GRADE)
    
    // ============================ CONSTRUCTORES ============================
    
    /**
     * Constructor for a simple report
     * @param content Report content
     */
    public Report(String content) {
        this.content = content;
        this.generationDate = LocalDateTime.now();
        this.generatedBy = "System";
        this.reportType = "GENERAL";
    }
    
    /**
     * Constructor for a report with generator info
     * @param content Report content
     * @param generatedBy Name of the person who generated the report
     */
    public Report(String content, String generatedBy) {
        this.content = content;
        this.generationDate = LocalDateTime.now();
        this.generatedBy = generatedBy;
        this.reportType = "GENERAL";
    }
    
    /**
     * Constructor for a complete report
     * @param content Report content
     * @param generatedBy Name of the person who generated the report
     * @param reportType Type of report (GENERAL, STUDENT, GRADE)
     */
    public Report(String content, String generatedBy, String reportType) {
        this.content = content;
        this.generationDate = LocalDateTime.now();
        this.generatedBy = generatedBy;
        this.reportType = reportType;
    }
    
    // ============================ MÉTODOS PRINCIPALES ============================
    
    /**
     * Prints the report to console
     */
    public void print() {
        System.out.println(content);
    }
    
    /**
     * Exports the report as a String
     * @return Complete report as String
     */
    public String export() {
        StringBuilder sb = new StringBuilder();
        sb.append(getHeader());
        sb.append(content);
        sb.append(getFooter());
        return sb.toString();
    }
    
    /**
     * Gets the report header with metadata
     * @return Formatted header
     */
    public String getHeader() {
        StringBuilder sb = new StringBuilder();
        sb.append("═".repeat(70)).append("\n");
        sb.append("   EDU-OBSERVADOR - SYSTEM REPORT\n");
        sb.append("═".repeat(70)).append("\n");
        sb.append("Report Type: ").append(reportType).append("\n");
        sb.append("Generated by: ").append(generatedBy).append("\n");
        sb.append("Date: ").append(getFormattedDate()).append("\n");
        sb.append("═".repeat(70)).append("\n\n");
        return sb.toString();
    }
    
    /**
     * Gets the report footer
     * @return Formatted footer
     */
    public String getFooter() {
        StringBuilder sb = new StringBuilder();
        sb.append("\n").append("═".repeat(70)).append("\n");
        sb.append("   End of Report\n");
        sb.append("   Generated by Edu-Observador System\n");
        sb.append("═".repeat(70)).append("\n");
        return sb.toString();
    }
    
    // ============================ MÉTODOS ESTÁTICOS PARA CREAR REPORTES ============================
    
    /**
     * Creates a general coexistence report (RF-11)
     * @param allStudents List of all students in the institution
     * @param coordinatorName Name of the coordinator generating the report
     * @return Complete Report object
     */
    public static Report createGeneralReport(List<Student> allStudents, String coordinatorName) {
        StringBuilder content = new StringBuilder();
        
        content.append("📊 GENERAL COEXISTENCE REPORT\n\n");
        
        int totalStudents = allStudents.size();
        int totalObservations = 0;
        int totalDisciplinary = 0;
        int totalAcademic = 0;
        int totalActive = 0;
        int totalCancelled = 0;
        
        for (Student student : allStudents) {
            totalObservations += student.getTotalObservations();
            totalDisciplinary += student.getDisciplinaryObservations().size();
            totalAcademic += student.getAcademicObservations().size();
            totalActive += student.getActiveObservationsCount();
            totalCancelled += student.getCancelledObservations().size();
        }
        
        content.append("📈 STATISTICS\n");
        content.append("─".repeat(50)).append("\n");
        content.append(String.format("   Total Students: %d\n", totalStudents));
        content.append(String.format("   Total Observations: %d\n", totalObservations));
        content.append(String.format("   • Disciplinary Observations: %d\n", totalDisciplinary));
        content.append(String.format("   • Academic Observations: %d\n", totalAcademic));
        content.append(String.format("   • Active Observations: %d\n", totalActive));
        content.append(String.format("   • Cancelled Observations: %d\n", totalCancelled));
        content.append("\n");
        
        content.append("📋 STUDENT DETAILS\n");
        content.append("─".repeat(50)).append("\n");
        
        for (Student student : allStudents) {
            content.append(String.format("\n   Student: %s (ID: %s)\n", student.getName(), student.getId()));
            content.append(String.format("   Grade: %s\n", student.getGrade() != null ? student.getGrade().getName() : "Not assigned"));
            content.append(String.format("   Total Observations: %d\n", student.getTotalObservations()));
            content.append(String.format("   Disciplinary: %d | Academic: %d\n", 
                student.getDisciplinaryObservations().size(), 
                student.getAcademicObservations().size()));
            content.append(String.format("   Active: %d | Cancelled: %d\n", 
                student.getActiveObservationsCount(),
                student.getCancelledObservations().size()));
        }
        
        return new Report(content.toString(), coordinatorName, "GENERAL");
    }
    
    /**
     * Creates a report for a specific student
     * @param student The student
     * @param requesterName Name of the person requesting the report
     * @return Complete Report object
     */
    public static Report createStudentReport(Student student, String requesterName) {
        StringBuilder content = new StringBuilder();
        
        content.append("📖 STUDENT ACADEMIC RECORD\n\n");
        content.append("─".repeat(50)).append("\n");
        content.append(String.format("   Student: %s\n", student.getName()));
        content.append(String.format("   ID: %s\n", student.getId()));
        content.append(String.format("   Grade: %s\n", student.getGrade() != null ? student.getGrade().getName() : "Not assigned"));
        content.append(String.format("   Status: %s\n", student.isActive() ? "Active" : "Inactive"));
        content.append("─".repeat(50)).append("\n\n");
        
        content.append("📋 OBSERVATIONS\n");
        content.append("─".repeat(50)).append("\n");
        
        List<Observation> observations = student.viewRecord();
        if (observations.isEmpty()) {
            content.append("   No observations recorded\n");
        } else {
            int index = 1;
            for (Observation obs : observations) {
                content.append(String.format("\n   [%d] %s\n", index++, obs.getObservationType()));
                content.append(String.format("       Date: %s\n", obs.getFormattedDate()));
                content.append(String.format("       Teacher: %s\n", obs.getCreatedByTeacher().getName()));
                content.append(String.format("       Description: %s\n", obs.getDescription()));
                content.append(String.format("       Details: %s\n", obs.getDetails()));
                if (!obs.isActive()) {
                    content.append(String.format("       ⚠️ CANCELLED: %s\n", obs.getCancellationJustification()));
                }
            }
        }
        
        content.append("\n").append("─".repeat(50)).append("\n");
        content.append(String.format("   SUMMARY\n"));
        content.append(String.format("   Total Observations: %d\n", student.getTotalObservations()));
        content.append(String.format("   Active: %d | Cancelled: %d\n", 
            student.getActiveObservationsCount(),
            student.getCancelledObservations().size()));
        
        return new Report(content.toString(), requesterName, "STUDENT");
    }
    
    /**
     * Creates a report for a specific grade
     * @param grade The grade
     * @param requesterName Name of the person requesting the report
     * @return Complete Report object
     */
    public static Report createGradeReport(Grade grade, String requesterName) {
        StringBuilder content = new StringBuilder();
        
        content.append("🏫 GRADE REPORT\n\n");
        content.append("─".repeat(50)).append("\n");
        content.append(String.format("   Grade: %s (ID: %d)\n", grade.getName(), grade.getId()));
        content.append(String.format("   Group Teacher: %s\n", 
            grade.getDocenteGrupo() != null ? grade.getDocenteGrupo().getName() : "Not assigned"));
        content.append(String.format("   Representative: %s\n", 
            grade.getRepresentante() != null ? grade.getRepresentante().getName() : "Not assigned"));
        content.append(String.format("   Total Students: %d\n", grade.getStudents().size()));
        content.append("─".repeat(50)).append("\n\n");
        
        content.append("📋 STUDENTS\n");
        content.append("─".repeat(50)).append("\n");
        
        int gradeTotalObservations = 0;
        int gradeTotalDisciplinary = 0;
        int gradeTotalAcademic = 0;
        
        for (Student student : grade.getStudents()) {
            gradeTotalObservations += student.getTotalObservations();
            gradeTotalDisciplinary += student.getDisciplinaryObservations().size();
            gradeTotalAcademic += student.getAcademicObservations().size();
            
            content.append(String.format("\n   • %s (ID: %s)\n", student.getName(), student.getId()));
            content.append(String.format("     Observations: %d (D:%d | A:%d)\n", 
                student.getTotalObservations(),
                student.getDisciplinaryObservations().size(),
                student.getAcademicObservations().size()));
        }
        
        content.append("\n").append("─".repeat(50)).append("\n");
        content.append("   GRADE SUMMARY\n");
        content.append(String.format("   Total Observations: %d\n", gradeTotalObservations));
        content.append(String.format("   Disciplinary: %d | Academic: %d\n", gradeTotalDisciplinary, gradeTotalAcademic));
        
        return new Report(content.toString(), requesterName, "GRADE");
    }
    
    // ============================ GETTERS Y SETTERS ============================
    
    public String getContent() {
        return content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    
    public LocalDateTime getGenerationDate() {
        return generationDate;
    }
    
    public void setGenerationDate(LocalDateTime generationDate) {
        this.generationDate = generationDate;
    }
    
    public String getGeneratedBy() {
        return generatedBy;
    }
    
    public void setGeneratedBy(String generatedBy) {
        this.generatedBy = generatedBy;
    }
    
    public String getReportType() {
        return reportType;
    }
    
    public void setReportType(String reportType) {
        this.reportType = reportType;
    }
    
    // ============================ MÉTODOS UTILITARIOS ============================
    
    /**
     * Gets formatted date string
     * @return Date formatted as "dd/MM/yyyy HH:mm:ss"
     */
    public String getFormattedDate() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        return generationDate.format(formatter);
    }
    
    /**
     * Saves the report to a file (simulated - would create a .txt file)
     * @param filename Name of the file to save
     * @return true if saved successfully
     */
    public boolean saveToFile(String filename) {
        // In a real implementation, this would write to a file
        System.out.println("📁 Report saved to: " + filename + ".txt");
        return true;
    }
    
    /**
     * Gets a summary of the report
     * @return Short summary string
     */
    public String getSummary() {
        return String.format("Report[type=%s, date=%s, by=%s, length=%d chars]",
            reportType, getFormattedDate(), generatedBy, content.length());
    }
    
    @Override
    public String toString() {
        return String.format("Report{type='%s', generatedBy='%s', date='%s', contentLength=%d}",
            reportType, generatedBy, getFormattedDate(), content.length());
    }
    
}
